#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	/// <summary>
	/// Dropdown list of the different program units available in the Victim Services branch.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Vsd_ProgramUnit
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CPU", 3, "#0000ff")]
		Cpu = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CSU", 2, "#0000ff")]
		Csu = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CVAP", 0, "#0000ff")]
		Cvap = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Gangs", 5, "#0000ff")]
		Gangs = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("REST", 4, "#0000ff")]
		Rest = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("VSU", 1, "#0000ff")]
		Vsu = 100000001,
	}
}
#pragma warning restore CS1591
