namespace Manager.Contract;


/// <summary>
/// Reason for the status of the Invoice
/// </summary>
public enum InvoiceStatusCode
{
    Cancelled = 100000009,
    Draft = 1,
    Duplicate = 865490002,
    Exception = 100000001,
    Negative = 100000005,
    OnHold = 100000008,
    Paid = 2,
    PendingCcReview = 865490001,
    PendingDecision = 865490000,
    Resubmit = 100000007,
    Submitted = 100000000,
}

public enum Origin
{
    AutoGenerated = 100000002,
    Email = 100000001,
    Manual = 100000003,
    Web = 100000000,
}

public record InvoiceQuery : IRequest<InvoiceResult>
{
    public Guid? ProgramId { get; set; }
    public Origin? Origin { get; set; }
    public DateTime? InvoiceDate { get; set; }
}

public record InvoiceResult(IEnumerable<Invoice> Invoices);

public record Invoice
{
    public Guid Id { get; set; }
    public StateCode StateCode { get; set; }
    public InvoiceStatusCode StatusCode { get; set; }
    public string Name { get; set; }
    public Guid? ContractId { get; set; }
    public Guid? OwnerId { get; set; }
}
