// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace Database.ProxyClasses.Enums
{
    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("XrmToolkit", "8.2.2.0")]
    public enum Document_DMERStatus
    {
        /// <summary>
        /// <para>Adjudicate</para>
        /// <para>Value = 100000000</para>
        /// </summary>
        [Description("Adjudicate")]
        Adjudicate = 100000000,

        /// <summary>
        /// <para>Reject</para>
        /// <para>Value = 100000001</para>
        /// </summary>
        [Description("Reject")]
        Reject = 100000001,

        /// <summary>
        /// <para>Clean Pass</para>
        /// <para>Value = 100000002</para>
        /// </summary>
        [Description("Clean Pass")]
        CleanPass = 100000002,

        /// <summary>
        /// <para>Manual Pass</para>
        /// <para>Value = 100000003</para>
        /// </summary>
        [Description("Manual Pass")]
        ManualPass = 100000003,
    }
}
